# karmasoc-posts
FROM node:6.8.0

# Create app directory
RUN mkdir -p /usr/src/app/ks-search
RUN mkdir -p /usr/src/app/ks-search/config
RUN mkdir -p /usr/src/app/ks-search/logs

COPY ./process.json /usr/src/app/ks-search
COPY ./config /usr/src/app/ks-search/config
COPY ./ks-search /usr/src/app/ks-search

WORKDIR /usr/src/app/ks-search

RUN npm install pm2 -g
RUN npm install --unsafe-perm=true

EXPOSE 44002

#CMD node index.js
CMD pm2 start --no-daemon  process.json --only ks-search --env docker